// One-time initializer for the on-chain poker_vault program.
// Run after `anchor deploy` lands the program on chain.
//
// Usage:
//   ANCHOR_PROVIDER_URL=https://api.devnet.solana.com \
//   ANCHOR_WALLET=~/.config/solana/id.json \
//   ts-node scripts/init-vault.ts <oracle-pubkey>

import { AnchorProvider, BN, Program, Wallet, web3 } from '@coral-xyz/anchor';
import { PublicKey } from '@solana/web3.js';
import { readFileSync } from 'node:fs';
import { homedir } from 'node:os';

const PROGRAM_ID = new PublicKey(process.env.NEXT_PUBLIC_VAULT_PROGRAM_ID ?? 'PoKeRVau1tXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
const USDC_MINT = new PublicKey(process.env.NEXT_PUBLIC_USDC_MINT ?? 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v');

async function main() {
  const oracle = process.argv[2];
  if (!oracle) {
    console.error('usage: init-vault.ts <oracle-pubkey>');
    process.exit(1);
  }
  const oraclePk = new PublicKey(oracle);

  const url = process.env.ANCHOR_PROVIDER_URL ?? 'https://api.devnet.solana.com';
  const walletPath = (process.env.ANCHOR_WALLET ?? '~/.config/solana/id.json').replace('~', homedir());
  const secret = JSON.parse(readFileSync(walletPath, 'utf8'));
  const kp = web3.Keypair.fromSecretKey(new Uint8Array(secret));
  const conn = new web3.Connection(url, 'confirmed');
  const provider = new AnchorProvider(conn, new Wallet(kp), { commitment: 'confirmed' });

  // Program IDL is generated by `anchor build` into apps/solana-program/target/idl/poker_vault.json
  const idl = JSON.parse(readFileSync(`${process.cwd()}/apps/solana-program/target/idl/poker_vault.json`, 'utf8'));
  const program = new Program(idl, provider);

  const [config] = PublicKey.findProgramAddressSync([Buffer.from('config')], PROGRAM_ID);
  const [vault] = PublicKey.findProgramAddressSync([Buffer.from('vault'), USDC_MINT.toBuffer()], PROGRAM_ID);
  const [vaultToken] = PublicKey.findProgramAddressSync([Buffer.from('vault_token'), USDC_MINT.toBuffer()], PROGRAM_ID);

  console.log('Initializing vault for program:', PROGRAM_ID.toBase58());
  console.log('  config:', config.toBase58());
  console.log('  vault:', vault.toBase58());
  console.log('  vaultToken:', vaultToken.toBase58());
  console.log('  oracle:', oraclePk.toBase58());

  // @ts-expect-error — generated method
  const sig = await program.methods
    .initialize(oraclePk)
    .accounts({
      admin: kp.publicKey,
      config,
      vault,
      usdcMint: USDC_MINT,
      vaultTokenAccount: vaultToken,
    })
    .rpc();
  console.log('Initialized:', sig);
}

main().catch(e => { console.error(e); process.exit(1); });
